apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: 651188399649.dkr.ecr.ap-southeast-2.amazonaws.com/eks-demo:latest_0.0  
      ports:
        - containerPort: 8085
